apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streaming-backend
  labels:
    service: streaming-backend
  name: streaming-backend
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        service: streaming-backend
    spec:
      imagePullSecrets:
      - name: pull-images-kickoff   
      containers:           
      - name: streaming-backend
        image: "images.kickoff.tech/backend.stream:1.0"                                    
        command: ["yarn", "start"]
        env:
        - name: SERVICE_NAME
          value: "streaming-backend"      
        - name: SERVER_PORT    
          value: "6000"
        - name: MAIL_HOST
          value: "smtp.stream.kickoff.tech"
        - name: MAIL_PORT
          value: "25"
        - name: MAIL_AUTH_USER
          value: ""
        - name: MAIL_AUTH_PASS
          value: ""
        - name: MAIL_SENDER
          value: "noreply@stream.kickoff.com"
        - name: MAIL_ADMINS
          value: "minhduongkhtn@gmail.com,kickoff.technology@gmail.com"        
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: DB_IP
          value: "database"
        - name: DB_PORT
          value: "27017"
        - name: DB_USERNAME
          value: "blabla"    
        - name: DB_PASSWORD
          value: "bloblo"      
        - name: DEBUG
          value: "*"
        ports:
        - containerPort: 6000
          name: svc-6000        
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    service: streaming-backend
  name: streaming-backend
spec:
  sessionAffinity: ClientIP
  ports:
  - name: "6000"
    port: 6000
    targetPort: 6000    
  selector:
    service: streaming-backend
  type: NodePort


